server:
  port: 8502

spring:
  application:
    name: ticket-service

  datasource:
    url: jdbc:mysql://localhost:3306/microserviceapp
    username: root
    password: microservis-app
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/